# Generated by Django 3.2.18 on 2023-05-12 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datetime', models.DateTimeField(auto_now_add=True, verbose_name='주문일자')),
                ('ship_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='배송지 주소')),
                ('ship_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='배송지 연락처')),
                ('shipped', models.BooleanField(default=False, verbose_name='배송완료여부')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='주문고객')),
                ('items_to_ship', models.ManyToManyField(to='boss.Product', verbose_name='판매상품')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='우편번호')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='주소')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='연락처')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
