# Generated by Django 3.2.18 on 2023-05-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='one_plus_one',
        ),
    ]
