# Generated by Django 3.2.18 on 2023-05-12 05:15

import boss.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0002_auto_20230511_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='event',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='이벤트'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=boss.models.Product.get_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
