# Generated by Django 3.2.18 on 2023-05-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss', '0004_auto_20230513_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='평점'),
        ),
    ]
