# Generated by Django 3.2.18 on 2023-05-12 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
